# Generated by Django 5.0.3 on 2024-04-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ckeditors_alter_category_options_alter_post_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ckeditors',
        ),
        migrations.AlterField(
            model_name='postvideo',
            name='video',
            field=models.FileField(upload_to='post-video/'),
        ),
    ]
